# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://ijasahd111971_db_user:Ijasahd123@cluster0.wxlkhca.mongodb.net/smartcampus_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true
server.port=8080
